apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: get
  name: get-caddyfile
data:
  Caddyfile: |-
    :8000 {
      proxy / https://conntroll.github.io/releases {
      }
    }

---
# Kubernetes Service & Deployment file
apiVersion: v1
kind: Service
metadata:
  name: get
spec:
  type: ClusterIP
  selector:
    app: get
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get
  labels:
    app: get
spec:
  replicas: 2
  selector:
    matchLabels:
      app: get
  template:
    metadata:
      labels:
        app: get
    spec:
      containers:
      - image: abiosoft/caddy
        name: get
        command:
        - caddy
        args:
        - -conf
        - /etc/Caddyfile
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/Caddyfile
          name: caddy-config
          subPath: Caddyfile
      volumes:
        - name: caddy-config
          configMap:
            name: get-caddyfile
            items:
              - key: Caddyfile
                path: Caddyfile
                mode: 0644
