apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hub
  annotations:
    ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
    # traefik.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/1,128.0.0.0/2,192.0.0.0/3,224.0.0.0/4"
    # kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: k0s.io
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
      - path: /k0s
        backend:
          serviceName: import-redir
          servicePort: 80
      - path: /grafana
        backend:
          serviceName: grafana
          servicePort: 80
      - path: /prometheus
        backend:
          serviceName: prometheus
          servicePort: 80
  - host: get.k0s.io
    http:
      paths:
      - path: /
        backend:
          serviceName: get
          servicePort: 80
  - host: hub.k0s.io
    http:
      paths:
      - path: /api
        backend:
          serviceName: hub
          servicePort: 80
  - host: staging.k0s.io
    http:
      paths:
      - path: /
        backend:
          serviceName: staging-web
          servicePort: 80
      - path: /api
        backend:
          serviceName: staging-hub
          servicePort: 80
  - host: prometheus-postgresql-adapter.k0s.io
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-postgresql-adapter
          servicePort: 80
  tls:
  - hosts:
    - prometheus-postgresql-adapter.k0s.io
    secretName: k0s.io
  - hosts:
    - staging.k0s.io
    secretName: k0s.io
  - hosts:
    - hub.k0s.io
    secretName: k0s.io
  - hosts:
    - k0s.io
    secretName: k0s.io
