# Source: k0s/templates/web.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: btwiuse/k0sio
        name: web
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: redeploy
          value: "asdf"
---
# Source: k0s/templates/web.yaml
# Kubernetes Service & Deployment file
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
# Source: k0s/templates/hub.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-hub
  template:
    metadata:
      labels:
        app: web-hub
    spec:
      containers:
      - name: web-hub
        image: btwiuse/k0s:latest
        args:
        - hub
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
        - name: redeploy
          value: "asdf"
---
# Source: k0s/templates/hub.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-hub
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: web-hub
