# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: default
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true

    [log]
    mode = console

    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [server]
    root_url = http://127.0.0.1:3000/monitoring/grafana/
    serve_from_sub_path = true

    [auth.anonymous]
    enabled = true

