apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-datasource
  namespace: default
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
    - name: Graphite
      orgId: 1
    - name: Prometheus
      orgId: 1
    - name: Prom
      orgId: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      uid: prometheus
      url: http://prometheus:80/monitoring/prometheus 
    # url: http://localhost:9090/monitoring/prometheus 
    # url: https://promana.milvzn.com/prometheus 
    # url: https://k0s.op.milvzn.com/prometheus 
    # url: http://prometheus-server.monitoring.svc.cluster.local
    # url: https://k0s.op.milvzn.com/prometheus 
    # url: http://prometheus-server.monitoring.svc.cluster.local
      isDefault: true
      editable: false
