# Source: k0s/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hub
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  # cert-manager.io/cluster-issuer: letsencrypt
  # cert-manager.io/acme-challenge-type: http01
spec:
  rules:
  - host: k0s.io
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
      - path: /k0s
        backend:
          serviceName: import-redir
          servicePort: 80
      - path: /grafana
        backend:
          serviceName: grafana
          servicePort: 80
      - path: /prometheus
        backend:
          serviceName: prometheus
          servicePort: 80
  - host: get.k0s.io
    http:
      paths:
      - path: /
        backend:
          serviceName: get
          servicePort: 80
  - host: hub.k0s.io
    http:
      paths:
      - path: /api
        backend:
          serviceName: hub
          servicePort: 80
  tls:
  - hosts:
    - get.k0s.io
    - hub.k0s.io
    - k0s.io
    secretName: k0s
