# Source: k0s/templates/web.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: web
  name: web-caddyfile
data:
  Caddyfile: |-
    {
      http_port 80
      debug
      admin off
    }

    :80 {
      route /* {
        reverse_proxy https://conntroll.github.io {
          header_up Host {http.reverse_proxy.upstream.hostport}
        }
      }
    }
