apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: caddy-auth-portal
  namespace: default
spec:
  selector:
    matchLabels:
      app: caddy-auth-portal
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: caddy-auth-portal
    spec:
      containers:
      - name: caddy-auth-portal
        image: btwiuse/k0s
        imagePullPolicy: IfNotPresent
        args:
        - caddy
        - run
        - -config
        - /etc/caddy/Caddyfile
        volumeMounts:
        - name: caddyfile
          mountPath: /etc/caddy/
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile
---
apiVersion: v1
kind: Service
metadata:
  name: caddy-auth-portal
  namespace: default
spec:
  ports:
  - name: caddy-auth-portal
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: caddy-auth-portal
  type: ClusterIP
