apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    # component: core
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: grafana
    # component: core
