# Source: k0s/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k16s.io
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  # cert-manager.io/cluster-issuer: letsencrypt
  # cert-manager.io/acme-challenge-type: http01
spec:
  rules:
  - host: k16s.io
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
      - path: /prometheus
        backend:
          serviceName: prometheus
          servicePort: 80
  tls:
  - hosts:
    - k16s.io
    secretName: k16s
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k16s
spec:
  secretName: k16s
  dnsNames:
  - k16s.io
  - '*.k16s.io'
  issuerRef:
    name: letsencrypt
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
