# Source: k0s/templates/hub.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chassis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chassis
  template:
    metadata:
      labels:
        app: chassis
    spec:
      containers:
      - name: chassis
        image: btwiuse/k0s:latest
        args:
        - chassis
        - :8000
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
        - name: redeploy
          value: "asdf"
