# Source: k0s/templates/digitalocean-dns.yaml
apiVersion: v1
data:
  access-token: {{ .Values.digitalocean.access_token | b64enc }}
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: cert-manager
type: Opaque
